import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { format } from 'date-fns';
import { Transaction } from '../types';
import { formatCurrencyFull } from './formatters';

export const exportTransactionsToPDF = async (
  transactions: Transaction[],
  currency: string,
  userName: string,
  totalBalance: number
) => {
  const dateStr = format(new Date(), 'MMMM dd, yyyy');
  
  const transactionRows = transactions.map(t => `
    <tr>
      <td style="padding: 10px; border-bottom: 1px solid #eee;">${format(new Date(t.date), 'MMM dd')}</td>
      <td style="padding: 10px; border-bottom: 1px solid #eee;">
        <strong>${t.title}</strong><br/>
        <small style="color: #666;">${t.categoryId}</small>
      </td>
      <td style="padding: 10px; border-bottom: 1px solid #eee; text-align: right; color: ${t.type === 'income' ? '#10b981' : '#ef4444'};">
        ${t.type === 'income' ? '+' : '-'}${formatCurrencyFull(t.amount, currency)}
      </td>
    </tr>
  `).join('');

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #7C6FFF; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { color: #7C6FFF; font-size: 24px; font-weight: bold; }
          .summary { display: flex; justify-content: space-between; background: #f8f9fa; padding: 20px; border-radius: 10px; margin-bottom: 30px; }
          .stat { text-align: center; }
          .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
          .stat-value { font-size: 18px; font-weight: bold; margin-top: 5px; }
          table { width: 100%; border-collapse: collapse; }
          th { text-align: left; background: #7C6FFF; color: #fff; padding: 12px; }
          .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #999; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">FinVault</div>
          <div style="text-align: right;">
            <div style="font-size: 14px; font-weight: bold;">${userName}</div>
            <div style="font-size: 12px; color: #666;">${dateStr}</div>
          </div>
        </div>

        <div class="summary">
          <div class="stat">
            <div class="stat-label">Total Balance</div>
            <div class="stat-value">${formatCurrencyFull(totalBalance, currency)}</div>
          </div>
          <div class="stat">
            <div class="stat-label">Transactions</div>
            <div class="stat-value">${transactions.length}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th style="border-top-left-radius: 8px;">Date</th>
              <th>Description</th>
              <th style="text-align: right; border-top-right-radius: 8px;">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${transactionRows}
          </tbody>
        </table>

        <div class="footer">
          Generated by FinVault - Your Smart Money Manager
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('PDF Export Error:', error);
    throw error;
  }
};

export const exportTransactionsToCSV = async (
  transactions: Transaction[],
  currency: string
) => {
  try {
    const header = 'Date,Title,Category,Type,Amount,Currency,Notes\n';
    const rows = transactions.map(t => {
      const escapedTitle = `"${t.title.replace(/"/g, '""')}"`;
      const escapedNotes = `"${(t.notes || '').replace(/"/g, '""')}"`;
      return `${format(new Date(t.date), 'yyyy-MM-dd')},${escapedTitle},"${t.categoryId}",${t.type},${t.amount},${currency},${escapedNotes}`;
    }).join('\n');

    const csvContent = header + rows;
    const fileName = `finvault_export_${format(new Date(), 'yyyy-MM-dd')}.csv`;
    const fileUri = FileSystem.documentDirectory + fileName;

    await FileSystem.writeAsStringAsync(fileUri, csvContent, {
      encoding: 'utf8',
    });

    await Sharing.shareAsync(fileUri, {
      mimeType: 'text/csv',
      dialogTitle: 'Export Transactions',
      UTI: 'public.comma-separated-values-text',
    });
  } catch (error) {
    console.error('CSV Export Error:', error);
    throw error;
  }
};
